packages:
  athom.rgbct-light: github://athom-tech/athom-configs/athom-rgbct-light.yaml

esphome:
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

api:
  encryption:
    key: ${api_key}

text_sensor:
  - platform: wifi_info
    bssid:
      name: "Connected BSSID"    

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  power_save_mode: none
  fast_connect: true
  manual_ip:
    static_ip: "192.168.1.${address}"
    gateway: 192.168.1.1
    subnet: 255.255.255.0
